// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/80060c94ef549c077a011977c2b5461bd0fd8947/remote-redux-devtools/index.d.ts
declare module "remote-redux-devtools" {

    type StringOrArray = string | string[];

    interface Config {
      name?: string;
      realtime?: boolean;
      hostname?: string;
      port?: number;
      secure?: boolean;
      filters?: {[key: string]: string[]};
      maxAge?: number;
      startOn?: StringOrArray;
      stopOn?: StringOrArray;
      sendOn?: StringOrArray;
      sendOnError?: number;
      sendTo?: string;
      id?: string;
    }

    function devTools(config?: Config): Function;

    namespace devTools {}

    export = devTools;
}
